code --install-extension ms-python.python
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension HookyQR.beautify
code --install-extension esbenp.prettier-vscode
code --install-extension felixfbecker.php-intellisense
code --install-extension xabikos.JavaScriptSnippets
code --install-extension Shan.code-settings-sync
code --install-extension abusaidm.html-snippets
code --install-extension christian-kohler.path-intellisense
code --install-extension Zignd.html-css-class-completion
code --install-extension msjsdiag.debugger-for-chrome
